/*
 * Copyright 2022 Square Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import Foundation
import Workflow

/// Convenience to execute an async function in a worker.
///
/// Example of using an async function.
/// ```
/// func render(state: State, context: RenderContext<Self>) -> MyScreen {
///     AsyncOperationWorker(myAsyncFunction)
///         .mapOutput { MyAction($0) }
///         .running(in: context, key: "UniqueKey")
///
///     return MyScreen()
/// }
/// ```
///
/// Example of using a closure.
/// ```
/// func render(state: State, context: RenderContext<Self>) -> MyScreen {
///     AsyncOperationWorker {
///         return await asyncFunctionCall()
///     }
///         .mapOutput { MyAction($0) }
///         .running(in: context, key: "UniqueKey")
///
///     return MyScreen()
/// }
/// ```
public struct AsyncOperationWorker<OutputType>: Worker {
    private let operation: () async -> OutputType

    public init(_ operation: @escaping () async -> OutputType) {
        self.operation = operation
    }

    public func run() async -> OutputType {
        await operation()
    }

    public typealias Output = OutputType

    public func isEquivalent(to otherWorker: AsyncOperationWorker) -> Bool {
        true
    }
}

extension RenderContext {
    /// Creates or updates a child workflow of the given type, performs a render
    /// pass, and returns the result.
    ///  
    /// The receiver is the context with which the workflow will be rendered.
    ///  
    /// - Returns: The `Rendering` generated by the workflow.
    /// `WorkflowType`.
    /// - Parameters:
    ///   - keyFile: A string that helps uniquely identifies this workflow.
    ///   - keyFunction: A string that helps uniquely identifies this workflow.
    ///   - keyLine: An integer that helps uniquely identifies this workflow.
    ///   - block: Any async closure or function to run. The return `Action`
    ///   type must match the context's `WorkflowType`.
    public func run<Action>(
        keyFile: StaticString = #file,
        keyFunction: StaticString = #function,
        keyLine: Int = #line,
        block: @escaping () async -> Action
    ) where Action: WorkflowAction, Action.WorkflowType == WorkflowType
    {
        AsyncOperationWorker(block)
            .running(in: self, key: "\(keyFile).\(keyFunction):\(keyLine)")
    }

    public func run<Output, Action>(
        keyFile: StaticString = #file,
        keyFunction: StaticString = #function,
        keyLine: Int = #line,
        block: @escaping () async -> Output,
        map: @escaping (Output) -> Action
    ) where Action: WorkflowAction, Action.WorkflowType == WorkflowType
    {
        AsyncOperationWorker(block)
            .running(in: self, key: "\(keyFile).\(keyFunction):\(keyLine)", outputMap: map)
    }

    public func run<Action>(
        keyFile: StaticString = #file,
        keyFunction: StaticString = #function,
        keyLine: Int = #line,
        block: @escaping () async throws -> Action,
        catch: @escaping (Error) -> Action
    ) where Action: WorkflowAction, Action.WorkflowType == WorkflowType
    {
        AsyncThrowingWorker(block)
            .running(in: self, key: "\(keyFile).\(keyFunction):\(keyLine)") { result -> Action in
                switch result {
                case .success(let output):
                    return output
                case .failure(let error):
                    return `catch`(error)
                }
            }
    }
}
