project 'WorkflowCombineSampleApp.xcodeproj'
platform :ios, '13.0'

target 'WorkflowCombineSampleApp' do
    pod 'Workflow', path: '../../Workflow.podspec', :testspecs => ['Tests']
    pod 'WorkflowUI', path: '../../WorkflowUI.podspec', :testspecs => ['Tests']
    pod 'WorkflowCombine', path: '../../WorkflowCombine.podspec'
    pod 'WorkflowReactiveSwift', path: '../../WorkflowReactiveSwift.podspec', :testspecs => ['Tests']

    target 'WorkflowCombineSampleAppUnitTests' do
        inherit! :search_paths

        pod 'Workflow', path: '../../Workflow.podspec', :testspecs => ['Tests']
        pod 'WorkflowCombine', path: '../../WorkflowCombine.podspec'
        pod 'WorkflowReactiveSwift', path: '../../WorkflowReactiveSwift.podspec', :testspecs => ['Tests']
        pod 'WorkflowUI', path: '../../WorkflowUI.podspec', :testspecs => ['Tests']
    end
end