project 'SampleApp.xcodeproj'
platform :ios, '14.0'

target 'SampleApp' do
    pod 'Workflow', path: '../../Workflow.podspec', :testspecs => ['Tests']
    pod 'WorkflowUI', path: '../../WorkflowUI.podspec', :testspecs => ['Tests']
end

target 'SampleAppTests' do
    pod 'Workflow', path: '../../Workflow.podspec', :testspecs => ['Tests']
    pod 'WorkflowUI', path: '../../WorkflowUI.podspec', :testspecs => ['Tests']
    pod 'WorkflowTesting', path: '../../WorkflowTesting.podspec', :testspecs => ['Tests']
end
