require_relative('../../version')

project 'Tutorial.xcodeproj'
platform :ios, WORKFLOW_IOS_DEPLOYMENT_TARGET

target 'Tutorial' do
    pod 'Workflow', path: '../../Workflow.podspec', :testspecs => ['Tests']
    pod 'WorkflowUI', path: '../../WorkflowUI.podspec', :testspecs => ['Tests']
    pod 'WorkflowSwiftUI', path: '../../WorkflowSwiftUI.podspec'
    pod 'ViewEnvironment', path: '../../ViewEnvironment.podspec'
    pod 'ViewEnvironmentUI', path: '../../ViewEnvironmentUI.podspec', :testspecs => ['Tests']
    pod 'WorkflowReactiveSwift', path: '../../WorkflowReactiveSwift.podspec', :testspecs => ['Tests']
    pod 'BackStackContainer', path: '../BackStackContainer/BackStackContainer.podspec'

    pod 'TutorialViews', path: 'Frameworks/TutorialViews/TutorialViews.podspec'
    pod 'TutorialBase', path: 'Frameworks/TutorialBase/TutorialBase.podspec', :testspecs => ['Tests']
    pod 'Tutorial1', path: 'Frameworks/Tutorial1Complete/Tutorial1.podspec'
    pod 'Tutorial2', path: 'Frameworks/Tutorial2Complete/Tutorial2.podspec'
    pod 'Tutorial3', path: 'Frameworks/Tutorial3Complete/Tutorial3.podspec'
    pod 'Tutorial4', path: 'Frameworks/Tutorial4Complete/Tutorial4.podspec', :testspecs => ['Tests']
    pod 'Tutorial5', path: 'Frameworks/Tutorial5Complete/Tutorial5.podspec', :testspecs => ['Tests']
end

target 'TutorialTests' do
    pod 'WorkflowTesting', path: '../../WorkflowTesting.podspec', :testspecs => ['Tests']
end
